### PR TITLE
Update form #26

### PR DESCRIPTION
**Pull request by Neobii**
This is a simple fix to update single files.

### CODE REVIEW

**Comment by advany** [comment]
+1

**Comment by advany** [comment]
+++1

**Comment by oaeide** [comment]
Nice!

**Comment by michalvalasek** [comment]
Is this going to be merged any time soon?

**Comment by aldeed** [comment]
I haven't had time to test, but I merged and released. Use at your own risk.

**Comment by michalvalasek** [comment]
Thank you!

**Comment by petermikitsh** [comment]
Is this only for forms `type='update/insert'`, excluding Meteor methods?

**Pull request merged**
